### ISSUE TITLE
Unable to establish WebSocket connection

### ISSUE THREAD

**Issue by aikeru** [tjanczuk/dante#1]
WebSockets are successfully disabled using:
`<webSocket enabled="false" />`
After running:
`c:\windows\system32\inetsrv\appcmd.exe unlock config -section:system.webServer/webSocket`
This is running on IIS8 / Windows Server 2012. I've tried turning off the firewall, that did not seem to help. There is nothing in \server.js.logs\0.txt (it is completely empty).
I am trying to browse either locally (http://localhost/dante/server.js) or over the network using Chrome (version 23.0.1271.97 and 24.0.1312.35).
MVC 4 / .net 4.5 is also installed and running fine on this machine.
To simplify things, I removed the web config completely from wwwroot.
`Unable to establish WebSocket connection to ws://localhost/dante/server.js/ws
WebSocket connection is closed.`

**Comment by tjanczuk** [comment]
Does the sample work when you self-host server.js in node.exe?
Which version of node.js and iisnode are you using?

**Comment by aikeru** [comment]
When I run it like this:
`c:\dante-master>node server.js`
I can then open `localhost:8888` and see the dante story gradually appear on the page (as it should) until it finishes and says `WebSocket connection is closed.`
Seems I am using `node-v0.8.16-x86.msi` for node.js. 
For IISNode I am not sure which version. I installed it from Web Platform Installer v4.0 called `IISNode for IIS (IIS Exists)` which says `Released 5/9/2012`. Perhaps that is somehow out of date.

I am not sure what the proper procedure procedure would be to remove/update IISNode (there doesn't seem to be an option in Web Platform Installer).

What is the proper way to check the version of IISNode?

**Comment by aikeru** [comment]
Ah 0.1.19 is the version (apparently you can double-click on the package in WebPI).
I decided to just try installing the latest and it works now!
Would you update your stackoverflow answer saying I needed to download the package as opposed to using the one from WebPI so it is up-to-date, and I can mark it as the correct answer? (that way you get the points)

**Comment by aikeru** [comment]
This is fixed.

**Comment by tjanczuk** [comment]
Right, iisnode supports websockets starting from version 0.2.0.

**Comment by aikeru** [comment]
Thanks for your help! :) Hopefully the WebPI package can get updated!
